### ISSUE TITLE
to add latex check to github workfliows

### ISSUE THREAD

**Issue by Graur** [objectionary/dejump#74]
We need to add a paper checks (`latexmk.yml`) similar to how we do it in EO:
```
name: latexmk
on:
  push:
    branches: master
    paths: 'paper/**'
  pull_request:
    branches: master
    paths: 'paper/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.5.0
        with:
          path: paper
          opts: -pdf
          packages: acmart cjk ffcode href-ul datetime fmtcount libertine paralist makecell footmisc currfile enumitem wrapfig lastpage biblatex titling svg trimspaces catchfile transparent textpos fvextra xstring framed environ totpages hyperxmp ifmtarg ncctools comment anyfontsize fdsymbol algpseudocodex algorithmicx stmaryrd preprint cyrillic cm-super babel-russian hyphen-russian lh to-be-determined cancel iexec csquotes
```
